config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:show]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  monetize :price_cents
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :book

  monetize :amount_cents

  enum state: [ :pending, :paid, :cancelled ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    order  = Order.create!(book_id: @book.id, amount: @book.price, state: :pending)

    redirect_to new_order_payment_path(order)
  end

  def show
    @order = Order.where(state: :paid).find(params[:id])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail])

    charge = Stripe::Charge.create(
      customer:     customer.id,
      amount:       @order.amount_cents,
      description:  "Paiement pour #{@order.book.title}, commande #{@order.id}",
      currency:     @order.amount.currency)

    @order.update(payment: charge.to_json, state: :paid)
    redirect_to order_path(@order)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = Order.where(state: :pending).find(params[:order_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/books/index.html.erb
<h1>Livres en vente :</h1>

<ul>
  <% @books.each do |book| %>
    <li><%= link_to(book.title, book_path(book)) %></li>
  <% end %>
</ul>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p>Prix : <%= humanized_money_with_symbol(@book.price) %></p>

<%= form_tag orders_path do %>
  <%= hidden_field_tag 'book_id', @book.id %>
  <%= submit_tag 'Acheter' %>
<% end %>

<%= link_to("Retour à la liste", root_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YnovDemoStripe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<h1>Confirmation de commande</h1>
<ul>
  <li>Status: <%= @order.state %></li>
  <li>Livre: <%= @order.book.title %></li>
  <li>Montant: <%= humanized_money_with_symbol(@order.amount) %></li>
</ul>

app/views/payments/new.html.erb
<h1>Récap achat du livre <%= @order.book.title %></h1>
<%= form_tag order_payments_path(@order) do %>
  Montant total: <%= humanized_money_with_symbol(@order.amount) %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="Achat d'un livre"
    data-email="<%= current_user.email %>"
    data-description="Livre <%= @order.book.title %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>
<% end %>